import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter, Oswald } from "next/font/google";
import Navbar from "./components/shared/Navbar";
import Footer from "./components/shared/Footer";
import FitLogProvider from "@/context/FitLogContext";
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body
        className={`${inter.variable} ${oswald.variable} min-h-full flex flex-col scroll-smooth`}
      >
        <FitLogProvider>
          <Navbar />
          <div>{children}</div>
          <Footer />
        </FitLogProvider>
      </body>
    </html>
  );
}
